kind: Service
apiVersion: v1
metadata:
  name: php-thangnv-service
spec:
  selector:
    app: php-thangnv
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-thangnv
  labels:
    app: php-thangnv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-thangnv
  template:
    metadata:
      labels:
        app: php-thangnv
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: php
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
#      volumes:
#      - name: demo
#        persistentVolumeClaim:
#          claimName: demo
